<?php
/**
 * Abstrakte Loader Klasse fuer Konfigurationsdateien oder aehnliches.
 *
 * Hier werden auch die includes aufgeloest. Dabei wird immer so vorgegangen,
 * das die spezielle Datei die allgemeine Datei einbindet und in der
 * speziellen Datei allgemeine Teile ergaenzen oder
 * ueberschreiben koennen.
 *
 */

require_once('FormatException.php');

abstract class AbstractFormat {
    const CMD_TYPE_REPLACE = 'replace';
    const CMD_TYPE_APPEND = 'append';
    const CMD_TYPE_MERGE = 'merge';

    protected $loadedFiles = array();

    protected $transformator = null;

    /**
     * @param string $filename
     * @param callable $transformator
     * @return array
     *
     * @throws FormatException
     */
    public function load($filename, $transformator=null) {
        if(isset($transformator)) $this->transformator = $transformator;
        $tmpFile = Environment::getTempFile($filename, 'formatcache', '.php');

        $rebuild = false;


        if(!file_exists($tmpFile) || $rebuild) {
            if(file_exists($filename)) {
                if(isset($this->loadedFiles[$filename])) {
                    throw new FormatException("Recursion detected, {$filename} already loaded!");
                }

                $data = $this->loadFile($filename);
                $this->loadedFiles[$filename] = true;

                $basedir = dirname($filename);
                $this->process($data, $basedir);

                unset($this->loadedFiles[$filename]);

                $content = "<?php // Generated by AbstractFormat of file '{$filename}'\n";
                $content .= "return " . var_export($data, true) . ";";
                file_put_contents($tmpFile, $content);
            } else {
                throw new FormatException("File {$filename} does not exist!");
            }
        } else {
            $data = include($tmpFile);
        }
        return $data;
    }

    /**
     * @param array $data
     * @param string $basedir
     */
    protected function process(array &$data, $basedir) {
        if(isset($this->transformator)) {
            /** @var callable $transformator */
            $transformator = $this->transformator;
            $transformator($data);
        }
        if(isset($data['include'])) {
            $this->processInclude($data, $basedir, $data['include']);
            unset($data['include']);
        }
        if(isset($data['supersede'])) {
            $this->processSupersede($data, $basedir, $data['supersede']);
            unset($data['supersede']);
        }
        reset($data);
    }

    /**
     * @param array $data
     * @param string $basedir
     * @param array $files
     */
    protected function processInclude(array &$data, $basedir, array $files) {
        foreach($files as $file) {
            $includeFile = ($file[0] === '/') ? $file:"{$basedir}/{$file}";
            $includeData = $this->load($includeFile);
            foreach($includeData as $key => $subData) {
                if(isset($subData)) {
                    if($key === 'include') {
                        $subdir = dirname("{$basedir}/{$file}");
                        $this->processInclude($data, $subdir, $subData);
                    } else if($key === 'supersede') {
                        $subdir = dirname("{$basedir}/{$file}");
                        $this->processSupersede($data, $subdir, $subData);
                    } else if(isset($data[$key])) {
                        $data[$key] = array_merge($subData, $data[$key]);
                    } else {
                        $data[$key] = $subData;
                    }
                }
            }
        }
    }

    /**
     * @param array $data
     * @param string $basedir
     * @param array $files
     */
    protected function processSupersede(array &$data, $basedir, array $files) {
        foreach($files as $file) {
            $supersedeFile = ($file[0] === '/') ? $file:"{$basedir}/{$file}";
            $supersedeData = $this->load($supersedeFile);
            foreach($supersedeData as $key => $subData) {
                if(isset($data[$key])) {
                    $data[$key] = array_merge($data[$key], $subData);
                } else {
                    $data[$key] = $subData;
                }
            }
        }
    }

    /**
     * @param string $filename
     * @return array
     */
    protected abstract function loadFile($filename);

    /**
     * @param mixed $data
     * @return mixed
     */
    public abstract function convert($data);
}